### ISSUE TITLE
Way to pass nthreads parameter to XGBooster() class

### ISSUE THREAD

**Issue by sreeraagbuyt** [bpachev/xgboost-php#3]
if this is not provided, in our case where we have 20 fpm processes, every class is trying to use all the cores and bringing the system down

**Comment by bpachev** [comment]
XGBoost provides such a parameter, and I will get to work on reflecting that in the wrapper. I took a two year break from work to serve a full-time mission for the Church of Jesus Christ of Latter Day Saints in the Ukraine, and was unable to maintain the repository in that time.
  XGBoost uses OpenMP for multithreading, and you can disable it via `set OMP_NUM_THREADS=1`. This of course is a hack, but it will provide a temporary solution until I fix the wrapper.
  Sorry for the inconvenience.

**Comment by bpachev** [comment]
@sreeraagbuyt 
  I've updated the XGBooster class with a method setParam that will allow you to control the number of threads for prediction without hacking the environment.
`$bst->setParam("nthread",1);` will do the trick.
